version: '3.1'

services:
    db:
      image: postgres
      restart: always
      env_file:
        - .env
    server:
      build: .
      restart: always
      env_file:
        - .env
      ports:
        - "8000:8000"
      depends_on:
        - db
      command: ["python3", "main.py"]
    test:
      build: .
      env_file:
        .env
      depends_on:
        - db
      command: ["pytest", "test_main.py"]