
name: Development Compose CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  run:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
      with:
        clean: false
    - name: "Create env file"
      run:
        
    - name: Run server
      run: docker compose -f docker-compose.dev.yml up --build -d --remove-orphans
permissions: 
  contents: write
