name: Prod Compose CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
      with:
        clean: false
        
    - name: Run server
      run: docker-compose -f docker-compose.dev.yml up --build -d --remove-orphans

permissions: 
  contents: write
