name: Docker Compose CI/CD

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: docker-compose version

    - name: Build and test Docker Compose
      run: |
        docker-compose build
        docker-compose run --rm test

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker Compose container to Docker Hub
      run: |
        docker-compose push

  build_and_push:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Pull Docker Compose container from Docker Hub
      run: |
        docker-compose pull

    - name: Build and push custom Docker image
      run: |
        docker build -t stranik28/server .
        docker push stranik28/server
  deploy:
    runs-on: self-hosted
    needs: build_and_push

    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Pull custom Docker image from Docker Hub
      run: |
        docker pull stranik28/server

    # Add additional steps for deployment
