name: Docker Compose CI/CD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: docker-compose version

    - name: Build and test Docker Compose
      run: |
        docker-compose build
        docker-compose run --rm tests # Замените "your_service_name" на имя вашего сервиса

  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: docker-compose version

    - name: Build and push Docker Compose
      run: |
        docker-compose build
        docker-compose push
        docker logout

  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: docker-compose version

    - name: Pull and deploy Docker Compose
      run: |
        docker-compose pull
        docker-compose up -d
